#ifndef XPM_INCLUDES_H
#define XPM_INCLUDES_H

#include "../Assets final/MC2/mainCharFront.xpm"
#include "../Images/mc1.xpm"
#include "../Assets final/mainCharAnimated/UP/mcUp8.xpm"
#include "../Assets final/mainCharAnimated/UP/mcUp2.xpm"
#include "../Assets final/mainCharAnimated/UP/mcUp3.xpm"
#include "../Assets final/mainCharAnimated/UP/mcUp4.xpm"
#include "../Assets final/mainCharAnimated/UP/mcUp5.xpm"
#include "../Assets final/mainCharAnimated/UP/mcUp6.xpm"
#include "../Assets final/mainCharAnimated/UP/mcUp7.xpm"
#include "../Assets final/mainCharAnimated/UP/mcUp1.xpm"
#include "../Assets final/mainCharAnimated/LEFT/mcLeft8.xpm"
#include "../Assets final/mainCharAnimated/LEFT/mcLeft2.xpm"
#include "../Assets final/mainCharAnimated/LEFT/mcLeft3.xpm"
#include "../Assets final/mainCharAnimated/LEFT/mcLeft4.xpm"
#include "../Assets final/mainCharAnimated/LEFT/mcLeft5.xpm"
#include "../Assets final/mainCharAnimated/LEFT/mcLeft6.xpm"
#include "../Assets final/mainCharAnimated/LEFT/mcLeft7.xpm"
#include "../Assets final/mainCharAnimated/LEFT/mcLeft1.xpm"
#include "../Assets final/mainCharAnimated/RIGHT/mcRight8.xpm"
#include "../Assets final/mainCharAnimated/RIGHT/mcRight2.xpm"
#include "../Assets final/mainCharAnimated/RIGHT/mcRight3.xpm"
#include "../Assets final/mainCharAnimated/RIGHT/mcRight4.xpm"
#include "../Assets final/mainCharAnimated/RIGHT/mcRight5.xpm"
#include "../Assets final/mainCharAnimated/RIGHT/mcRight6.xpm"
#include "../Assets final/mainCharAnimated/RIGHT/mcRight7.xpm"
#include "../Assets final/mainCharAnimated/RIGHT/mcRight1.xpm"
#include "../Assets final/mainCharAnimated/DOWN/mcDown8.xpm"
#include "../Assets final/mainCharAnimated/DOWN/mcDown2.xpm"
#include "../Assets final/mainCharAnimated/DOWN/mcDown3.xpm"
#include "../Assets final/mainCharAnimated/DOWN/mcDown4.xpm"
#include "../Assets final/mainCharAnimated/DOWN/mcDown5.xpm"
#include "../Assets final/mainCharAnimated/DOWN/mcDown6.xpm"
#include "../Assets final/mainCharAnimated/DOWN/mcDown7.xpm"
#include "../Assets final/mainCharAnimated/DOWN/mcDown1.xpm"

#include "../Assets final/letters/a.xpm"
#include "../Assets final/letters/b.xpm"
#include "../Assets final/letters/c.xpm"
#include "../Assets final/letters/d.xpm"
#include "../Assets final/letters/e.xpm"
#include "../Assets final/letters/f.xpm"
#include "../Assets final/letters/g.xpm"
#include "../Assets final/letters/h.xpm"
#include "../Assets final/letters/i.xpm"
#include "../Assets final/letters/j.xpm"
#include "../Assets final/letters/k.xpm"
#include "../Assets final/letters/l.xpm"
#include "../Assets final/letters/m.xpm"
#include "../Assets final/letters/n.xpm"
#include "../Assets final/letters/o.xpm"
#include "../Assets final/letters/p.xpm"
#include "../Assets final/letters/q.xpm"
#include "../Assets final/letters/r.xpm"
#include "../Assets final/letters/s.xpm"
#include "../Assets final/letters/t.xpm"
#include "../Assets final/letters/u.xpm"
#include "../Assets final/letters/v.xpm"
#include "../Assets final/letters/w.xpm"
#include "../Assets final/letters/x.xpm"
#include "../Assets final/letters/y.xpm"
#include "../Assets final/letters/z.xpm"

#include "../Assets final/selected_letters/a.xpm"
#include "../Assets final/selected_letters/b.xpm"
#include "../Assets final/selected_letters/c.xpm"
#include "../Assets final/selected_letters/d.xpm"
#include "../Assets final/selected_letters/e.xpm"
#include "../Assets final/selected_letters/f.xpm"
#include "../Assets final/selected_letters/g.xpm"
#include "../Assets final/selected_letters/h.xpm"
#include "../Assets final/selected_letters/i.xpm"
#include "../Assets final/selected_letters/j.xpm"
#include "../Assets final/selected_letters/k.xpm"
#include "../Assets final/selected_letters/l.xpm"
#include "../Assets final/selected_letters/m.xpm"
#include "../Assets final/selected_letters/n.xpm"
#include "../Assets final/selected_letters/o.xpm"
#include "../Assets final/selected_letters/p.xpm"
#include "../Assets final/selected_letters/q.xpm"
#include "../Assets final/selected_letters/r.xpm"
#include "../Assets final/selected_letters/s.xpm"
#include "../Assets final/selected_letters/t.xpm"
#include "../Assets final/selected_letters/u.xpm"
#include "../Assets final/selected_letters/v.xpm"
#include "../Assets final/selected_letters/w.xpm"
#include "../Assets final/selected_letters/x.xpm"
#include "../Assets final/selected_letters/y.xpm"
#include "../Assets final/selected_letters/z.xpm"

#include "../Images/mouse/mouse_normal.xpm"
#include "../Assets final/tileset/ground.xpm"
#endif
