#ifndef XPM_INCLUDES_H
#define XPM_INCLUDES_H

#include "Images/mainCharFront.xpm"
#include "Images/mc1.xpm"
#include "../Assets Final/mainCharAnimated/UP/mcp8.xpm"
#include "../Assets Final/mainCharAnimated/UP/mcUp2.xpm"
#include "../Assets Final/mainCharAnimated/UP//mcUp3.xpm"
#include "../Assets Final/mainCharAnimated/UP/mcUp4.xpm"
#include "../Assets Final/mainCharAnimated/UP/mcUp5.xpm"
#include "../Assets Final/mainCharAnimated/UP/mcUp6.xpm"
#include "../Assets Final/mainCharAnimated/UP/mcUp7.xpm"
#include "../Assets Final/mainCharAnimated/UP/mcUp1.xpm"
#include "../Assets final/letters/a.xpm"
#include "../Assets final/letters/b.xpm"
#include "../Assets final/letters/c.xpm"
#include "../Assets final/letters/d.xpm"
#include "../Assets final/letters/e.xpm"
#include "../Assets final/letters/f.xpm"
#include "../Assets final/letters/g.xpm"
#include "../Assets final/letters/h.xpm"
#include "../Assets final/letters/i.xpm"
#include "../Assets final/letters/j.xpm"
#include "../Assets final/letters/k.xpm"
#include "../Assets final/letters/l.xpm"
#include "../Assets final/letters/m.xpm"
#include "../Assets final/letters/n.xpm"
#include "../Assets final/letters/o.xpm"
#include "../Assets final/letters/p.xpm"
#include "../Assets final/letters/q.xpm"
#include "../Assets final/letters/r.xpm"
#include "../Assets final/letters/s.xpm"
#include "../Assets final/letters/t.xpm"
#include "../Assets final/letters/u.xpm"
#include "../Assets final/letters/v.xpm"
#include "../Assets final/letters/w.xpm"
#include "../Assets final/letters/x.xpm"
#include "../Assets final/letters/y.xpm"
#include "../Assets final/letters/z.xpm"
#include "../Assets final/obstacle/Boulder.xpm"
#include "../Assets final/tileset/ground.xpm"

#endif
